# Generated by Django 4.2.2 on 2023-06-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default='2001-03-16'),
            preserve_default=False,
        ),
    ]
